### ISSUE TITLE
Unable to debug() find-result with FileStorage dependency

### ISSUE THREAD

**Issue by tfohlmeister** [graemetait/cakephp-file-storage-behavior#2]
In my setup here I have two models: 
- Files (which `actsAs` the FileStorage)
- Events, which `belongsTo` Files

Whenever I do a `$events = $this->Events->find('all');` and try to `debug($result)` the result, I get an empty output. This doesn't happen if I skip the `Event['File']` property, e.g. by only selecting `debug($events['Event'])`. I am currently using the latest [DebugKit](https://github.com/cakephp/debug_kit).

Any suggestion on how to fix this? This is a major issue, as it also affects JSON encoding of results (empty as well).

**Comment by tfohlmeister** [comment]
So I digged a little deeper and found that indeed the `content` property results in empty responses (I save files in the database).
Another interesting find is that `Debugger::dump($events['File']['content'])` outputs correct data while `debug($events['File']['content'])` just outputs nothing (as described before). 
I guess there is something wrong with encoding here.

**Comment by graemetait** [comment]
Not sure what's happening here but I'm away on a trip at the moment just checking in on my phone, so will look into it when I'm back.

**Comment by graemetait** [comment]
Sorry to leave this for so long.  As far as I can tell this seems to be a problem with Cake's debug() function not liking binary data. Native PHP functions like var_dump() and print_r() will both print the full output fine.

JSON doesn't support binary either, so I suspect you'll have to do something extra to encode the file as text to get json_encode() to play nice, probably using base64_encode() or similar.
